export const momTheme = {
  background: '#FFF0F5',
  header: '#FFB3C6',
  headerShadow: '#e8849a',
  headerText: 'white',
  subText: '#9B7FA8',
  cardText: '#4A3F5C',
  cardSubText: '#6B5B7A',
  aboutButton: '#EDD9FF',
  aboutButtonShadow: '#b08fd4',
  footerText: '#C9B1E8',
  userBubble: '#C9B1E8',
  userBubbleShadow: '#b08fd4',
  botBubble: '#FFB3C6',
  botBubbleShadow: '#e8849a',
  inputBorder: '#FFB3C6',
  inputBackground: '#FFF0F5',
  quickQuestionsBorder: '#F0E0EA',
  typingBubble: '#FFE0EC',
  typingText: '#9B7FA8',
  logoText: '#C678A0',
  logoTagline: '#B5D5FF',
};

export const dadTheme = {
  background: '#F4F7F5',
  header: '#5B8FA8',
  headerShadow: '#3d6b82',
  headerText: 'white',
  subText: '#5C7A6B',
  cardText: '#2C3E35',
  cardSubText: '#4A6355',
  aboutButton: '#D6E8D0',
  aboutButtonShadow: '#8ab49a',
  footerText: '#8ab49a',
  userBubble: '#8BBFA8',
  userBubbleShadow: '#5C9A80',
  botBubble: '#B8D4C8',
  botBubbleShadow: '#7aaa94',
  inputBorder: '#8BBFA8',
  inputBackground: '#F4F7F5',
  quickQuestionsBorder: '#D6E8D0',
  typingBubble: '#D6E8D0',
  typingText: '#5C7A6B',
  logoText: '#5B8FA8',
  logoTagline: '#8BBFA8',
};

export const momDarkTheme = {
  background: '#1A0F14',
  header: '#8B3A52',
  headerShadow: '#5c1f33',
  headerText: 'white',
  subText: '#C9A0B8',
  cardText: '#F0D6E8',
  cardSubText: '#C9A0B8',
  aboutButton: '#2D1A28',
  aboutButtonShadow: '#5c1f33',
  footerText: '#9B6080',
  userBubble: '#6B3A5C',
  userBubbleShadow: '#4a1f3f',
  botBubble: '#2D1A28',
  botBubbleShadow: '#5c1f33',
  inputBorder: '#6B3A5C',
  inputBackground: '#2D1A28',
  quickQuestionsBorder: '#3D2030',
  typingBubble: '#2D1A28',
  typingText: '#C9A0B8',
  logoText: '#E87AAC',
  logoTagline: '#9B6080',
};

export const dadDarkTheme = {
  background: '#0F1A1F',
  header: '#2E5F78',
  headerShadow: '#1a3d52',
  headerText: 'white',
  subText: '#7AAFCA',
  cardText: '#D0E8F2',
  cardSubText: '#7AAFCA',
  aboutButton: '#1A2E3A',
  aboutButtonShadow: '#1a3d52',
  footerText: '#4A8FA8',
  userBubble: '#2E6080',
  userBubbleShadow: '#1a3d52',
  botBubble: '#1A2E3A',
  botBubbleShadow: '#1a3d52',
  inputBorder: '#2E6080',
  inputBackground: '#1A2E3A',
  quickQuestionsBorder: '#1E3845',
  typingBubble: '#1A2E3A',
  typingText: '#7AAFCA',
  logoText: '#5BAFD4',
  logoTagline: '#4A8FA8',
};

export const getTheme = (parentGender: string, isDarkMode: boolean) => {
  if (isDarkMode) return parentGender === 'dad' ? dadDarkTheme : momDarkTheme;
  return parentGender === 'dad' ? dadTheme : momTheme;
};
